---

variables:
  GIT_SSL_NO_VERIFY: "true"
  CI_PROJECT_URL: "https://jstarbuild.ivv.nasa.gov"

stages:
  - build
  - test

build-synopsis-job:
    stage: build
    tags:
      - itc-inp
    script:
        - ls
