---

variables:
  GIT_SSL_NO_VERIFY: "true"
  CI_PROJECT_URL: "https://jstarbuild.ivv.nasa.gov"

default:
  image: ubuntu:latest

stages:
  - build
  - test

build-and-test-synopsis:
  stage: build
  tags:
    - itc-inp
  script:
    - apt update
    - apt-get install cmake g++ make -y
    - mkdir build
    - cd build
    - cmake ..
    - make 
    - make test



