---

variables:
  GIT_SSL_NO_VERIFY: "true"
  CI_PROJECT_URL: "https://jstarbuild.ivv.nasa.gov"

stages:
  - build
  - test

build-synopsis-job:
  stage: build
  tags:
    - itc-inp
  script:
    - apt update
    - apt-get install cmake -y
    - ls
    - cmake -S . -B build
    - cmake --build build

test-synopsis-job:
  stage: test
  script:
    - cd build && ctest


