---

variables:
  GIT_SSL_NO_VERIFY: "true"
  CI_PROJECT_URL: "https://jstarbuild.ivv.nasa.gov"

default:
  image: i386/ubuntu:bionic

stages:
  - build_and_test

build-and-test-synopsis:
  stage: build_and_test
  tags:
    - itc-inp
  script:
    - apt update
    - apt-get install cmake g++ g++-multilib gcc-multilib sqlite3 libsqlite3-dev libsqlite3-dev:i386 sqlite3:i386 make -y
    - mkdir build
    - cd build
    - cmake ..
    - make 
    - make test



