---

variables:
  GIT_SSL_NO_VERIFY: "true"
  CI_PROJECT_URL: "https://jstarbuild.ivv.nasa.gov"

default:
  image: ubuntu:latest

stages:
  - build
  - test

build-synopsis-job:
  stage: build
  tags:
    - itc-inp
  script:
    - apt update
    - apt-get install cmake g++ make -y
    - pwd
    - mkdir build
    - pwd
    - ls
    - cd build
    - cmake ..
    #- cmake /builds/ITC/synopsis/synopsis -B /builds/ITC/synopsis/synopsis/build
    #- cmake --build /builds/ITC/synopsis/synopsis/build
    - make 

test-synopsis-job:
  stage: test
  script:
    - cd /builds/ITC/synopsis/synopsis/build && ctest


